const semuakelas = [
    {
      id: 1,
      image: "https://ayomakan.oss-ap-southeast-5.aliyuncs.com/article/ARTICLE-AYOMAKAN_20231103140453.jpg",
      star1: "fa-solid fa-star",
      star2: "fa-solid fa-star",
      star3: "fa-solid fa-star",
      star4: "fa-solid fa-star",
      star5: "fa-solid fa-star-half-stroke",
      title: "Cappucino",
      price: "Rp. 5.500",
      buy: "Beli Kelas",
      delay: "1300",
    },
    {
        id: 2,
        image: "https://media-cdn.tripadvisor.com/media/photo-s/11/b8/aa/d2/mochacino-ginger.jpg",
        star1: "fa-solid fa-star",
        star2: "fa-solid fa-star",
        star3: "fa-solid fa-star",
        star4: "fa-solid fa-star",
        star5: "fa-solid fa-star-half-stroke",
        title: "Mochacino",
        price: "Rp. 5.000",
        buy: "Beli Kelas",
        delay: "1300",
      },
      {
        id: 3,
        image: "https://www.nescafe.com/id/sites/default/files/Kopi-Hitam-Americano-dan-Espresso%2C-Apa-Bedanya%2C-Ya.jpg",
        star1: "fa-solid fa-star",
        star2: "fa-solid fa-star",
        star3: "fa-solid fa-star",
        star4: "fa-solid fa-star",
        star5: "fa-solid fa-star-half-stroke",
        title: "Americano",
        price: "Rp. 6.000",
        buy: "Beli Kelas",
        delay: "1300",
      },
      {
        id: 4,
        image: "https://d1r9hss9q19p18.cloudfront.net/uploads/2017/03/affogato_1280x720-sumber-.jpg",
        star1: "fa-solid fa-star",
        star2: "fa-solid fa-star",
        star3: "fa-solid fa-star",
        star4: "fa-solid fa-star",
        star5: "fa-solid fa-star-half-stroke",
        title: "Affogato",
        price: "Rp. 10.000",
        buy: "Beli Kelas",
        delay: "1300",
      },
      {
          id: 5,
          image: "https://www.nescafe.com/id/sites/default/files/Fakta-Menarik-Seputar-CaffВ-Latte%2C-Kopi-Susu-ala-Italia.gif",
          star1: "fa-solid fa-star",
          star2: "fa-solid fa-star",
          star3: "fa-solid fa-star",
          star4: "fa-solid fa-star",
          star5: "fa-solid fa-star-half-stroke",
          title: "Latte",
          price: "Rp. 2.230.000",
          buy: "Beli Kelas",
          delay: "1300",
        },
        {
          id: 6,
          image: "https://kopikita.id/wp-content/uploads/2022/12/espresso-vs-expresso.jpg",
          star1: "fa-solid fa-star",
          star2: "fa-solid fa-star",
          star3: "fa-solid fa-star",
          star4: "fa-solid fa-star",
          star5: "fa-solid fa-star-half-stroke",
          title: "expresso",
          price: "Rp. 7.500",
          buy: "Beli Kelas",
          delay: "1300",
        },
        {
            id: 7,
            image: "https://www.nescafe.com/gb/sites/default/files/2023-08/long-black-coffee-header-1066x1066.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "Black coffe",
            price: "Rp. 12.500",
            buy: "Beli Kelas",
            delay: "1300",
          },
          {
              id: 8,
              image: "https://id.jura.com/-/media/global/images/coffee-recipes/images-redesign-2020/espresso_doppio_2000x1400px.jpg",
              star1: "fa-solid fa-star",
              star2: "fa-solid fa-star",
              star3: "fa-solid fa-star",
              star4: "fa-solid fa-star",
              star5: "fa-solid fa-star-half-stroke",
              title: "doppio coffee",
              price: "Rp. 13.000",
              buy: "Beli Kelas",
              delay: "1300",
            },
            {
              id: 9,
              image: "https://static.toiimg.com/thumb/86699095.cms?width=1200&height=900",
              star1: "fa-solid fa-star",
              star2: "fa-solid fa-star",
              star3: "fa-solid fa-star",
              star4: "fa-solid fa-star",
              star5: "fa-solid fa-star-half-stroke",
              title: "Flat white",
              price: "Rp. 4.500",
              buy: "Beli Kelas",
              delay: "1300",
            },
            ];

export default semuakelas;